### ISSUE TITLE
请求错误

### ISSUE THREAD

**Issue by yizhitian1145** [EvolvedGhost/mirai-novelai-naifu#1]
content=/ai text sky]请求错误：java.net.ConnectException: Failed to connect to /127.0.0.1:6969
这个是怎么回事？
是api的问题吗
系统是Windows
mirai版本是2.13.4

**Comment by EvolvedGhost** [comment]
这个得你自己本机部署一个novelai并且能在这个地址上正常跑。只使用过：https://b23.tv/xnbXwpd 进行过测试
